version: "3.9"
services:
  db:
    image: postgres:15.2-alpine
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=boris
      - POSTGRES_PASSWORD=boris
      - POSTGRES_DB=books
    networks:
      - default
    ports:
      - '5432:5433'
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - db
    environment:
      - URL=postgres://boris:boris@db:5432/books